theme: https://github.com/pages-themes/slate

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"

collections:
  docs:
    output: true

name: autospec name heeere

plugins:
  - jekyll-sitemap